### ISSUE TITLE
error in android module

### ISSUE THREAD

**Issue by usama7628674** [oddcod3/Phantom-Evasion#19]
@oddcod3 I got the following while generating android payload

![image](https://user-images.githubusercontent.com/29252277/41636099-ee50b894-7465-11e8-8cd2-82ed0dcc1750.png)

**Comment by oddcod3** [comment]
@usama7628674 yes you are right
Android and osx modules will be reworked in the next release

**Comment by cashbea** [comment]
2.0.1 release also doesn't work

**Comment by usama7628674** [comment]
Chane java to 10 version using update-alternatives

**Comment by cashbea** [comment]
@usama7628674 thanks for your advice. but 

Selection    Path                                            Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/java-10-openjdk-amd64/bin/java      1101      auto mode
  1            /usr/lib/jvm/java-10-openjdk-amd64/bin/java      1101      manual mode
  2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

Press <enter> to keep the current choice[*], or type selection number:

it aleady was chosen.

**Comment by usama7628674** [comment]
@cashbea Select option 2 then try again

**Comment by usama7628674** [comment]
@oddcod3 Probably a problen in apktool.The following link may help you.
https://bugs.kali.org/view.php?id=5126

**Comment by cashbea** [comment]
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at org.jf.dexlib2.writer.DexWriter.writeAnnotationDirectories(DexWriter.java:698)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:267)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:246)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:419)
	at brut.androlib.Androlib.buildSources(Androlib.java:350)
	at brut.androlib.Androlib.build(Androlib.java:302)
	at brut.androlib.Androlib.build(Androlib.java:269)
	at brut.apktool.Main.cmdBuild(Main.java:238)
	at brut.apktool.Main.main(Main.java:76)
[+] Infected file /root/Desktop/TheFatRat/temp/app_backdoored.apk ready.
 
\e[1;31m 
[x] There was an error in the creation of your RAT APK file , the possible reasons are :
- The architecture of the file is not for android
- The original APK is protected
- It was not possible to inject the payload in the hook you selected (in this case select a different hook point)

**Comment by cashbea** [comment]
when option 0 was chosen, there was no error. but output.apk didn't work.
