### ISSUE TITLE
Unable to bind an android payload 

### ISSUE THREAD

**Issue by nomanslan** [oddcod3/Phantom-Evasion#26]
I'm unable to bind a payload I don't know what the issue is. Can anyone please help to solve the issue.
This is the error I'm getting every time.

 
[>] Smaling...

I: Using Apktool 2.3.3
brut.directory.PathNotExist: apktool.yml

[>] Please insert output filename: kuchbhi.apk
Traceback (most recent call last):
  File "phantom-evasion.py", line 441, in <module>
    complete_menu()
  File "phantom-evasion.py", line 295, in complete_menu
    Phantom_lib.droidmare_launcher()
  File "Setup/Phantom_lib.py", line 1799, in droidmare_launcher
    apksigner()
  File "Setup/Phantom_lib.py", line 1635, in apksigner
    os.rename('msf_rebuild.apk',Apk_out)
OSError: [Errno 2] No such file or directory

**Comment by sam14x** [comment]
this is the solution that i found and worked for me
Use
sudo apktool empty-framework-dir

then delete the smali folders and previous projects data from phantom evasion folder
then run the setup script (#7 i guess) from phantom_evasion.py

Hope this works

**Comment by thisisjayakumar** [comment]
I have got this issue.. Please Help me sort out.
os.rename("msf_smali/smali/com/metasploit","msf_smali/smali/com/" + ModOpt["Metaspl"])
OSError: [Errno 2] No such file or directory
