### ISSUE TITLE
Unable to install phantom-evasion

### ISSUE THREAD

**Issue by leiferdjango** [oddcod3/Phantom-Evasion#32]
Hello,

I got this error in the middle of the instalation process, Im running Debian 9, the wine python version is  3.4 

>] Trying to autoinstall:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libc6-dev-i386 : Depends: libc6-i386 (= 2.24-11+deb9u3) but 2.27-6 is to be installed
                  Depends: libc6-dev (= 2.24-11+deb9u3) but 2.27-6 is to be installed
                  Recommends: gcc-multilib but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
[+] apktool                              [Found]
[+] apktool.jar file                     [Found]
[+] gcc                                  [Found]
[+] mingw-w64                            [Found]
[+] pyinstaller                          [Found]
[+] apksigner                            [Found]
[+] openssl                              [Found]
[+] strip                                [Found]
[+] wine                                 [Found]
[+] Wine Environment check
[Wine] Python Found
[Wine] Pyinstaller Found
[>] Metasploit-Framework  [Found]

[>] Completed!!

[DISCLAIMER]:Phantom-Evasion is intended to be used for legal security
purposes only any other use is not under the responsibility of the developer

[+] Developed by: Diego Cornacchini  

[+] GITHUB: https://github.com/oddcod3 

[+] VERSION: 1.2 

[+] MODULES: 24

[+] NEW FEATURES: Pure C meterpreter stager,Persistence modules 

Traceback (most recent call last):
  File "./phantom-evasion.py", line 439, in <module>
    Phantom_lib.xmr_miner()
  File "Setup/Phantom_lib.py", line 614, in xmr_miner
    subprocess.call(['tmux','send-keys','-t','phantom-miner','\"\x03\"','C-m'], stdout=open(os.devnull,'wb'), stderr=open(os.devnull,'wb'))
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by leiferdjango** [comment]
The dependencies apearly to be updated Im able to run Phantom OK.
