### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by M0dred** [oddcod3/Phantom-Evasion#56]
python phantom-evasion.py

[+] VERSION: 2.0.1 

[+] MODULES: 51

[+] NEW FEATURES: C meterpreter reverse https stager, Thread hijack & PE inject modules, Exe signer with online certificate spoofer  

Traceback (most recent call last):
  File "phantom-evasion.py", line 716, in <module>
    Phantom_lib.xmr_miner()
  File "Setup/Phantom_lib.py", line 775, in xmr_miner
    subprocess.call(['tmux','send-keys','-t','phantom-miner','\"\x03\"','C-m'], stdout=open(os.devnull,'wb'), stderr=open(os.devnull,'wb'))
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by kelvinmatheka** [comment]
Am having the same issue someone help please

**Comment by thecowmilk** [comment]
Im having this error too
