### ISSUE TITLE
Error while generating apk payload (android/meterpreter/reverse_tcp)

### ISSUE THREAD

**Issue by eqelibari** [oddcod3/Phantom-Evasion#72]
[>] Generating code...

[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 10178 bytes
Saved as: msf_gen.apk

[>] Baksmaling...

Error: Unable to access jarfile Setup/apk_sign/apktool_2.4.1.jar

[>] Obfuscating Smali code...

Traceback (most recent call last):
  File "./phantom-evasion.py", line 402, in <module>
    CompleteMenu()
  File "./phantom-evasion.py", line 190, in CompleteMenu
    Phantom_lib.ModuleLauncher(module_type)
  File "Setup/Phantom_lib.py", line 937, in ModuleLauncher
    LoadExecModule(M_type,ModOpt)
  File "Setup/Phantom_lib.py", line 591, in LoadExecModule
    ApkSmaliObfuscator_android(ModOpt)
  File "Modules/payloads/MsfvenomObfuscateBackdoor_android.py", line 287, in ApkSmaliObfuscator_android
    os.rename("msf_smali/smali/com/metasploit","msf_smali/smali/com/" + ModOpt["Metaspl"])
OSError: [Errno 2] No such file or directory

**Comment by delgiu87** [comment]
about error jarfile is enough to update with option 7 first  , for the error of "no platform" I am still waiting and trying solution .

seem same problem occur in different tool for the same problem of upgrade of jar that lost the support until someone can upgrade in the code or downgrade jar
