### ISSUE TITLE
smali????????????????

### ISSUE THREAD

**Issue by delgiu87** [oddcod3/Phantom-Evasion#74]
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 10186 bytes
Saved as: msf_gen.apk

[>] Baksmaling...

Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Destination directory (/root/Scrivania/phevasion/msf_smali) already exists. Use -f switch if you want to overwrite it.

[>] Obfuscating Smali code...

Traceback (most recent call last):
  File "phantom-evasion.py", line 402, in <module>
    CompleteMenu()
  File "phantom-evasion.py", line 190, in CompleteMenu
    Phantom_lib.ModuleLauncher(module_type)
  File "Setup/Phantom_lib.py", line 937, in ModuleLauncher
    LoadExecModule(M_type,ModOpt)
  File "Setup/Phantom_lib.py", line 591, in LoadExecModule
    ApkSmaliObfuscator_android(ModOpt)
  File "Modules/payloads/MsfvenomObfuscateBackdoor_android.py", line 287, in ApkSmaliObfuscator_android
    os.rename("msf_smali/smali/com/metasploit","msf_smali/smali/com/" + ModOpt["Metaspl"])
FileNotFoundError: [Errno 2] No such file or directory: 'msf_smali/smali/com/metasploit' -> 'msf_smali/smali/com/cqptgqyl'

**Comment by vij7661** [comment]
delete msf_smali file and rerun the script

**Comment by sam14x** [comment]
this is the solution that i found and worked for me
Use 
# sudo apktool empty-framework-dir
then delete the smali folders and previous projects data from phantom evasion folder
then run the setup script (#7 i guess) from phantom_evasion.py

Hope this works
