### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Txoka** [oddcod3/Phantom-Evasion#80]
Hi.
When trying to create some backdoors does not matter what configuration i use it always gives me this compilation error.

```
Source.c: In function ‘main’:
Source.c:42:1: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
 for (WORD VqcxSaUsJYiBVbc = 0;VqcxSaUsJYiBVbc < NgoawoZWQUTVg->FileHeader.NumberOfSections;VqcxSaUsJYiBVbc++) {
 ^
Source.c:42:1: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
```

This did not happen when i downloaded the tool, i used it some time, then installed some more tools, updated packets and did several actions, then this started happening.
(Im on Kali Linux)

**Comment by Txoka** [comment]
Also (i dont know if i should oppen another issue), when trying to spoof certificates it gives me the following:

```
Traceback (most recent call last):
  File "/home/txoka/GIT/Phantom-Evasion/phantom-evasion.py", line 402, in <module>
    CompleteMenu()
  File "/home/txoka/GIT/Phantom-Evasion/phantom-evasion.py", line 125, in CompleteMenu
    Phantom_lib.ModuleLauncher(module_type)
  File "Setup/Phantom_lib.py", line 964, in ModuleLauncher
    ExeSigner(ModOpt["Outfile"],ModOpt["SpoofCert"],ModOpt["descr"])
  File "Setup/Phantom_lib.py", line 439, in ExeSigner
    pfx = crypto.PKCS12Type()
AttributeError: 'module' object has no attribute 'PKCS12Type'
```
This happens since i downloaded the tool, and still happens after updating packets.

**Comment by Txoka** [comment]
going to /Phantom-Evasion/Setup/Phantom_lib.py and adding "-std=c99" to every compiler call in AutoCompiler solves the first thing.

**Comment by Txoka** [comment]
Changing:
```
pfx = crypto.PKCS12Type()
```
to
```
try:
    pfx = crypto.PKCS12()
except AttributeError:
    pfx = crypto.PKCS12Type()
```
in Exesigner in the same file than avobe solves the signing error.
