### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by aaaaajie** [oddcod3/Phantom-Evasion#81]
Problems encountered when using Windows modules

Traceback (most recent call last):
  File "./phantom-evasion.py", line 402, in <module>
    CompleteMenu()
  File "./phantom-evasion.py", line 125, in CompleteMenu
    Phantom_lib.ModuleLauncher(module_type)
  File "Setup/Phantom_lib.py", line 943, in ModuleLauncher
    AutoCompiler(M_type,ModOpt)
  File "Setup/Phantom_lib.py", line 251, in AutoCompiler
    subprocess.call([Compiler,ModOpt["Resfile"],'Source.c','-o',ModOpt["Outfile"],'-mwindows','-Wno-cpp'])
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by KaiserClement** [comment]
You have to use python 3 so that it works.
So first update your python and then type this in phantom-evasion's working directory -> python3 phantom-evasion.py
