### ISSUE TITLE
Problem with obfuscating smali code

### ISSUE THREAD

**Issue by fkay9** [oddcod3/Phantom-Evasion#83]
When I run the tool I get this problem.

Traceback (most recent call last):
  File "phantom-evasion.py", line 402, in <module>
    CompleteMenu()
  File "phantom-evasion.py", line 190, in CompleteMenu
    Phantom_lib.ModuleLauncher(module_type)
  File "Setup/Phantom_lib.py", line 937, in ModuleLauncher
    LoadExecModule(M_type,ModOpt)
  File "Setup/Phantom_lib.py", line 591, in LoadExecModule
    ApkSmaliObfuscator_android(ModOpt)
  File "Modules/payloads/MsfvenomObfuscateBackdoor_android.py", line 287, in ApkSmaliObfuscator_android
    os.rename("msf_smali/smali/com/metasploit","msf_smali/smali/com/" + ModOpt["Metaspl"])
FileNotFoundError: [Errno 2] No such file or directory: 'msf_smali/smali/com/metasploit' -> 'msf_smali/smali/com/bfocizv'

**Comment by baptiste314** [comment]
Same

**Comment by J35t3rOP** [comment]
Same error here
