### ISSUE TITLE
Setup error Kali Linux 2020.4

### ISSUE THREAD

**Issue by ghost** [oddcod3/Phantom-Evasion#87]
I run kali linux 2020.4 from a raspberry pi 4 and got this error when I tried installing.

```
:~/Phantom-Evasion$ python3 phantom-evasion.py --setup


                       _                 _
                 _ __ | |__   __ _ _ __ | |_ ___  _ __ ___
                | '_ \| '_ \ / _` | '_ \| __/ _ \| '_ ` _ \
                | |_) | | | | (_| | | | | || (_) | | | | | |
                | .__/|_| |_|\__,_|_| |_|\__\___/|_| |_| |_|
                |_|   / _ \ \ / / _` / __| |/ _ \| '_ \
                     |  __/\ V / (_| \__ \ | (_) | | | |
                      \___| \_/ \__,_|___/_|\___/|_| |_|
                                                        v3.0


[<DISCLAIMER>]: Phantom-Evasion is intended to be used for legal security
purposes only any other use is not under the responsibility of the developer

[>] Author: Diego Cornacchini (oddcod3)

[>] Github: https://github.com/oddcod3

[>] Version: 3.0

[>] Using Python Version: 3.8.6
Traceback (most recent call last):
  File "phantom-evasion.py", line 396, in <module>
    Phantom_lib.CmdlineLauncher(sys.argv)
  File "Setup/Phantom_lib.py", line 1295, in CmdlineLauncher
    AutoSetup()
  File "Setup/Setup_lib.py", line 63, in AutoSetup
    OtherLinuxSetup()
TypeError: OtherLinuxSetup() missing 1 required positional argument: 'rel'
```

Any help?

**Comment by ghost** [comment]
Type "uname -a" and lets see what system that you are running
